// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeddingOrchestrator.Api.Data;

#nullable disable

namespace WeddingOrchestrator.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717112110_AddExSpouseRelationshipTypes")]
    partial class AddExSpouseRelationshipTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FamilyGroup")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("FatherId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MotherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FatherId");

                    b.HasIndex("MotherId");

                    b.HasIndex("FirstName", "LastName");

                    b.ToTable("People");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.PersonRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromPersonId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("RelationshipTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ToPersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelationshipTypeId");

                    b.HasIndex("ToPersonId");

                    b.HasIndex("FromPersonId", "ToPersonId", "RelationshipTypeId")
                        .IsUnique();

                    b.ToTable("PersonRelationships");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.RelationshipType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("GenerationDelta")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TypeLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TypeCode")
                        .IsUnique();

                    b.ToTable("RelationshipTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "DIRECT",
                            GenerationDelta = 1,
                            IsActive = true,
                            TypeCode = "FATHER",
                            TypeLabel = "Father"
                        },
                        new
                        {
                            Id = 2,
                            Category = "DIRECT",
                            GenerationDelta = 1,
                            IsActive = true,
                            TypeCode = "MOTHER",
                            TypeLabel = "Mother"
                        },
                        new
                        {
                            Id = 3,
                            Category = "DIRECT",
                            GenerationDelta = -1,
                            IsActive = true,
                            TypeCode = "SON",
                            TypeLabel = "Son"
                        },
                        new
                        {
                            Id = 4,
                            Category = "DIRECT",
                            GenerationDelta = -1,
                            IsActive = true,
                            TypeCode = "DAUGHTER",
                            TypeLabel = "Daughter"
                        },
                        new
                        {
                            Id = 5,
                            Category = "DIRECT",
                            GenerationDelta = 0,
                            IsActive = true,
                            TypeCode = "HUSBAND",
                            TypeLabel = "Husband"
                        },
                        new
                        {
                            Id = 6,
                            Category = "DIRECT",
                            GenerationDelta = 0,
                            IsActive = true,
                            TypeCode = "WIFE",
                            TypeLabel = "Wife"
                        },
                        new
                        {
                            Id = 7,
                            Category = "DIRECT",
                            GenerationDelta = 0,
                            IsActive = true,
                            TypeCode = "BROTHER",
                            TypeLabel = "Brother"
                        },
                        new
                        {
                            Id = 8,
                            Category = "DIRECT",
                            GenerationDelta = 0,
                            IsActive = true,
                            TypeCode = "SISTER",
                            TypeLabel = "Sister"
                        },
                        new
                        {
                            Id = 9,
                            Category = "EXTENDED",
                            GenerationDelta = 2,
                            IsActive = true,
                            TypeCode = "GRANDFATHER",
                            TypeLabel = "Grandfather"
                        },
                        new
                        {
                            Id = 10,
                            Category = "EXTENDED",
                            GenerationDelta = 2,
                            IsActive = true,
                            TypeCode = "GRANDMOTHER",
                            TypeLabel = "Grandmother"
                        },
                        new
                        {
                            Id = 11,
                            Category = "EXTENDED",
                            GenerationDelta = -2,
                            IsActive = true,
                            TypeCode = "GRANDSON",
                            TypeLabel = "Grandson"
                        },
                        new
                        {
                            Id = 12,
                            Category = "EXTENDED",
                            GenerationDelta = -2,
                            IsActive = true,
                            TypeCode = "GRANDDAUGHTER",
                            TypeLabel = "Granddaughter"
                        },
                        new
                        {
                            Id = 13,
                            Category = "EXTENDED",
                            GenerationDelta = 1,
                            IsActive = true,
                            TypeCode = "UNCLE",
                            TypeLabel = "Uncle"
                        },
                        new
                        {
                            Id = 14,
                            Category = "EXTENDED",
                            GenerationDelta = 1,
                            IsActive = true,
                            TypeCode = "AUNT",
                            TypeLabel = "Aunt"
                        },
                        new
                        {
                            Id = 15,
                            Category = "EXTENDED",
                            GenerationDelta = -1,
                            IsActive = true,
                            TypeCode = "NEPHEW",
                            TypeLabel = "Nephew"
                        },
                        new
                        {
                            Id = 16,
                            Category = "EXTENDED",
                            GenerationDelta = -1,
                            IsActive = true,
                            TypeCode = "NIECE",
                            TypeLabel = "Niece"
                        },
                        new
                        {
                            Id = 17,
                            Category = "EXTENDED",
                            GenerationDelta = 0,
                            IsActive = true,
                            TypeCode = "COUSIN",
                            TypeLabel = "Cousin"
                        },
                        new
                        {
                            Id = 18,
                            Category = "INLAW",
                            GenerationDelta = 1,
                            IsActive = true,
                            TypeCode = "FATHER_IN_LAW",
                            TypeLabel = "Father-in-law"
                        },
                        new
                        {
                            Id = 19,
                            Category = "INLAW",
                            GenerationDelta = 1,
                            IsActive = true,
                            TypeCode = "MOTHER_IN_LAW",
                            TypeLabel = "Mother-in-law"
                        },
                        new
                        {
                            Id = 20,
                            Category = "INLAW",
                            GenerationDelta = -1,
                            IsActive = true,
                            TypeCode = "SON_IN_LAW",
                            TypeLabel = "Son-in-law"
                        },
                        new
                        {
                            Id = 21,
                            Category = "INLAW",
                            GenerationDelta = -1,
                            IsActive = true,
                            TypeCode = "DAUGHTER_IN_LAW",
                            TypeLabel = "Daughter-in-law"
                        },
                        new
                        {
                            Id = 22,
                            Category = "INLAW",
                            GenerationDelta = 0,
                            IsActive = true,
                            TypeCode = "BROTHER_IN_LAW",
                            TypeLabel = "Brother-in-law"
                        },
                        new
                        {
                            Id = 23,
                            Category = "INLAW",
                            GenerationDelta = 0,
                            IsActive = true,
                            TypeCode = "SISTER_IN_LAW",
                            TypeLabel = "Sister-in-law"
                        },
                        new
                        {
                            Id = 24,
                            Category = "STEP",
                            GenerationDelta = 1,
                            IsActive = true,
                            TypeCode = "STEP_FATHER",
                            TypeLabel = "Step-father"
                        },
                        new
                        {
                            Id = 25,
                            Category = "STEP",
                            GenerationDelta = 1,
                            IsActive = true,
                            TypeCode = "STEP_MOTHER",
                            TypeLabel = "Step-mother"
                        },
                        new
                        {
                            Id = 26,
                            Category = "STEP",
                            GenerationDelta = -1,
                            IsActive = true,
                            TypeCode = "STEP_SON",
                            TypeLabel = "Step-son"
                        },
                        new
                        {
                            Id = 27,
                            Category = "STEP",
                            GenerationDelta = -1,
                            IsActive = true,
                            TypeCode = "STEP_DAUGHTER",
                            TypeLabel = "Step-daughter"
                        },
                        new
                        {
                            Id = 28,
                            Category = "STEP",
                            GenerationDelta = 0,
                            IsActive = true,
                            TypeCode = "STEP_BROTHER",
                            TypeLabel = "Step-brother"
                        },
                        new
                        {
                            Id = 29,
                            Category = "STEP",
                            GenerationDelta = 0,
                            IsActive = true,
                            TypeCode = "STEP_SISTER",
                            TypeLabel = "Step-sister"
                        },
                        new
                        {
                            Id = 30,
                            Category = "ADOPTED",
                            GenerationDelta = 1,
                            IsActive = true,
                            TypeCode = "ADOPTIVE_FATHER",
                            TypeLabel = "Adoptive Father"
                        },
                        new
                        {
                            Id = 31,
                            Category = "ADOPTED",
                            GenerationDelta = 1,
                            IsActive = true,
                            TypeCode = "ADOPTIVE_MOTHER",
                            TypeLabel = "Adoptive Mother"
                        },
                        new
                        {
                            Id = 32,
                            Category = "ADOPTED",
                            GenerationDelta = -1,
                            IsActive = true,
                            TypeCode = "ADOPTED_SON",
                            TypeLabel = "Adopted Son"
                        },
                        new
                        {
                            Id = 33,
                            Category = "ADOPTED",
                            GenerationDelta = -1,
                            IsActive = true,
                            TypeCode = "ADOPTED_DAUGHTER",
                            TypeLabel = "Adopted Daughter"
                        },
                        new
                        {
                            Id = 34,
                            Category = "HALF",
                            GenerationDelta = 0,
                            IsActive = true,
                            TypeCode = "HALF_BROTHER",
                            TypeLabel = "Half-brother"
                        },
                        new
                        {
                            Id = 35,
                            Category = "HALF",
                            GenerationDelta = 0,
                            IsActive = true,
                            TypeCode = "HALF_SISTER",
                            TypeLabel = "Half-sister"
                        },
                        new
                        {
                            Id = 36,
                            Category = "STEP",
                            GenerationDelta = 2,
                            IsActive = true,
                            TypeCode = "STEP_GRANDFATHER",
                            TypeLabel = "Step-grandfather"
                        },
                        new
                        {
                            Id = 37,
                            Category = "STEP",
                            GenerationDelta = 2,
                            IsActive = true,
                            TypeCode = "STEP_GRANDMOTHER",
                            TypeLabel = "Step-grandmother"
                        },
                        new
                        {
                            Id = 38,
                            Category = "STEP",
                            GenerationDelta = -2,
                            IsActive = true,
                            TypeCode = "STEP_GRANDSON",
                            TypeLabel = "Step-grandson"
                        },
                        new
                        {
                            Id = 39,
                            Category = "STEP",
                            GenerationDelta = -2,
                            IsActive = true,
                            TypeCode = "STEP_GRANDDAUGHTER",
                            TypeLabel = "Step-granddaughter"
                        },
                        new
                        {
                            Id = 40,
                            Category = "INLAW",
                            GenerationDelta = -2,
                            IsActive = true,
                            TypeCode = "GRANDSON_IN_LAW",
                            TypeLabel = "Grandson-in-law"
                        },
                        new
                        {
                            Id = 41,
                            Category = "INLAW",
                            GenerationDelta = -2,
                            IsActive = true,
                            TypeCode = "GRANDDAUGHTER_IN_LAW",
                            TypeLabel = "Granddaughter-in-law"
                        },
                        new
                        {
                            Id = 42,
                            Category = "INLAW",
                            GenerationDelta = 2,
                            IsActive = true,
                            TypeCode = "GRANDFATHER_IN_LAW",
                            TypeLabel = "Grandfather-in-law"
                        },
                        new
                        {
                            Id = 43,
                            Category = "INLAW",
                            GenerationDelta = 2,
                            IsActive = true,
                            TypeCode = "GRANDMOTHER_IN_LAW",
                            TypeLabel = "Grandmother-in-law"
                        },
                        new
                        {
                            Id = 44,
                            Category = "DIRECT",
                            GenerationDelta = 0,
                            IsActive = true,
                            TypeCode = "EX_WIFE",
                            TypeLabel = "Ex Wife"
                        },
                        new
                        {
                            Id = 45,
                            Category = "DIRECT",
                            GenerationDelta = 0,
                            IsActive = true,
                            TypeCode = "EX_HUSBAND",
                            TypeLabel = "Ex Husband"
                        });
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.RoleTypeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("RoleTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Groom"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bride"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Father of the Groom"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mother of the Groom"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Father of the Bride"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Mother of the Bride"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Paternal Grandfather of the Groom"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Paternal Grandmother of the Groom"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Maternal Grandfather of the Groom"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Maternal Grandmother of the Groom"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Paternal Grandfather of the Bride"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Paternal Grandmother of the Bride"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Maternal Grandfather of the Bride"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Maternal Grandmother of the Bride"
                        });
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RelativeFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SongCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SongCategoryId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.SongCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SongCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Groom Songs"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Bride Songs"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Father Songs"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Mother Songs"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Grandmother Songs"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Grandfather Songs"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Intro for Father/Mother"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Wedding Intros"
                        });
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.Wedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfWedding")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<int?>("FatherMotherWeddingSongIntroBrideId")
                        .HasColumnType("int");

                    b.Property<int?>("FatherMotherWeddingSongIntroGroomId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WeddingSongIntroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FatherMotherWeddingSongIntroBrideId");

                    b.HasIndex("FatherMotherWeddingSongIntroGroomId");

                    b.HasIndex("WeddingSongIntroId");

                    b.ToTable("Weddings");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.WeddingDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InWeddingRelationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedToPersonId")
                        .HasColumnType("int");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.Property<int?>("SongId")
                        .HasColumnType("int");

                    b.Property<int>("WeddingId")
                        .HasColumnType("int");

                    b.Property<string>("WeddingSide")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InWeddingRelationTypeId");

                    b.HasIndex("PersonId");

                    b.HasIndex("RelatedToPersonId");

                    b.HasIndex("SongId");

                    b.HasIndex("WeddingId");

                    b.ToTable("WeddingDetails");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.Person", b =>
                {
                    b.HasOne("WeddingOrchestrator.Api.Models.Person", "Father")
                        .WithMany()
                        .HasForeignKey("FatherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WeddingOrchestrator.Api.Models.Person", "Mother")
                        .WithMany()
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Father");

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.PersonRelationship", b =>
                {
                    b.HasOne("WeddingOrchestrator.Api.Models.Person", "FromPerson")
                        .WithMany()
                        .HasForeignKey("FromPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WeddingOrchestrator.Api.Models.RelationshipType", "RelationshipType")
                        .WithMany("Relationships")
                        .HasForeignKey("RelationshipTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WeddingOrchestrator.Api.Models.Person", "ToPerson")
                        .WithMany()
                        .HasForeignKey("ToPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromPerson");

                    b.Navigation("RelationshipType");

                    b.Navigation("ToPerson");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.Song", b =>
                {
                    b.HasOne("WeddingOrchestrator.Api.Models.SongCategory", "Category")
                        .WithMany("Songs")
                        .HasForeignKey("SongCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.Wedding", b =>
                {
                    b.HasOne("WeddingOrchestrator.Api.Models.Song", "FatherMotherWeddingSongIntroBride")
                        .WithMany()
                        .HasForeignKey("FatherMotherWeddingSongIntroBrideId");

                    b.HasOne("WeddingOrchestrator.Api.Models.Song", "FatherMotherWeddingSongIntroGroom")
                        .WithMany()
                        .HasForeignKey("FatherMotherWeddingSongIntroGroomId");

                    b.HasOne("WeddingOrchestrator.Api.Models.Song", "WeddingSongIntro")
                        .WithMany()
                        .HasForeignKey("WeddingSongIntroId");

                    b.Navigation("FatherMotherWeddingSongIntroBride");

                    b.Navigation("FatherMotherWeddingSongIntroGroom");

                    b.Navigation("WeddingSongIntro");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.WeddingDetail", b =>
                {
                    b.HasOne("WeddingOrchestrator.Api.Models.RelationshipType", "WeddingRelationType")
                        .WithMany()
                        .HasForeignKey("InWeddingRelationTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WeddingOrchestrator.Api.Models.Person", "Person")
                        .WithMany("WeddingDetails")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WeddingOrchestrator.Api.Models.Person", "RelatedToPerson")
                        .WithMany()
                        .HasForeignKey("RelatedToPersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WeddingOrchestrator.Api.Models.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WeddingOrchestrator.Api.Models.Wedding", "Wedding")
                        .WithMany("Details")
                        .HasForeignKey("WeddingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("RelatedToPerson");

                    b.Navigation("Song");

                    b.Navigation("Wedding");

                    b.Navigation("WeddingRelationType");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.Person", b =>
                {
                    b.Navigation("WeddingDetails");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.RelationshipType", b =>
                {
                    b.Navigation("Relationships");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.SongCategory", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.Wedding", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
