// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeddingOrchestrator.Api.Data;

#nullable disable

namespace WeddingOrchestrator.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FatherId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MotherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FatherId");

                    b.HasIndex("MotherId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RelativeFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SongCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SongCategoryId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.SongCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SongCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Groom Songs"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Bride Songs"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Father Songs"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Mother Songs"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Grandmother Songs"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Grandfather Songs"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Intro for Father/Mother"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Wedding Intros"
                        });
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.Wedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfWedding")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Weddings");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.WeddingRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FreeTextName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.Property<int>("WeddingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("WeddingId", "RoleType")
                        .IsUnique();

                    b.ToTable("WeddingRoles");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.WeddingRoleSongAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentSlot")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<int>("WeddingRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.HasIndex("WeddingRoleId", "AssignmentSlot")
                        .IsUnique();

                    b.ToTable("WeddingRoleSongAssignments");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.Person", b =>
                {
                    b.HasOne("WeddingOrchestrator.Api.Models.Person", "Father")
                        .WithMany()
                        .HasForeignKey("FatherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WeddingOrchestrator.Api.Models.Person", "Mother")
                        .WithMany()
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Father");

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.Song", b =>
                {
                    b.HasOne("WeddingOrchestrator.Api.Models.SongCategory", "Category")
                        .WithMany("Songs")
                        .HasForeignKey("SongCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.WeddingRole", b =>
                {
                    b.HasOne("WeddingOrchestrator.Api.Models.Person", "Person")
                        .WithMany("WeddingRoles")
                        .HasForeignKey("PersonId");

                    b.HasOne("WeddingOrchestrator.Api.Models.Wedding", "Wedding")
                        .WithMany("Roles")
                        .HasForeignKey("WeddingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Wedding");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.WeddingRoleSongAssignment", b =>
                {
                    b.HasOne("WeddingOrchestrator.Api.Models.Song", "Song")
                        .WithMany("Assignments")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WeddingOrchestrator.Api.Models.WeddingRole", "WeddingRole")
                        .WithMany("SongAssignments")
                        .HasForeignKey("WeddingRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("WeddingRole");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.Person", b =>
                {
                    b.Navigation("WeddingRoles");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.Song", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.SongCategory", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.Wedding", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("WeddingOrchestrator.Api.Models.WeddingRole", b =>
                {
                    b.Navigation("SongAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
